### ISSUE TITLE
Floating window gets "broken"

### ISSUE THREAD

**Issue by eemed** [cideM/yui#12]
Floating window has markdownurl highlighted objects which "break" the floating window.
![fixthis](https://user-images.githubusercontent.com/30186515/86537032-e31f5300-bef4-11ea-81a8-e08af721357d.png)

This could be fixed with 
```
:hi markdownUrl guibg=none
```

**Comment by cideM** [comment]
Does the `fix-markdown` branch solve this?

**Comment by eemed** [comment]
`fix-markdown` branch fixes the issue.

**Comment by cideM** [comment]
Fixed by #15
