### ISSUE TITLE
Terminal colors

### ISSUE THREAD

**Issue by eemed** [cideM/yui#14]
Terminal colors should be different currently many of them are black.
For example using ag with the current settings looks like this:
![agcolors](https://user-images.githubusercontent.com/30186515/86628086-079d2d00-bfd2-11ea-9449-022094b0d286.png)
The blocks are the matched text.

**Comment by cideM** [comment]
The thing is that many terminal apps sometimes use colors in strange ways which results in almost impossible to solve situations, especially with regards to light themes. In this case for example it would be good to know what `Ag` is using so that it results in this kind of highlight.

**Comment by eemed** [comment]
You can add me as a contributor. I agree that light themes can be problematic, but we should at least give them a chance by making the colors different. The end result may not be perfect with all programs but most should be fine.

**Comment by cideM** [comment]
Yup but for that we need to first figure out why this looks so broken, as in which combination of terminal colors results in this output.

**Comment by eemed** [comment]
The issue is with the 4th terminal color that is yellow normally. Here is an example with tomorrow light themes yellow color
```
Color: yellow                  #eab700    ~
...
Term colors: black red green yellow blue black black black
Term colors: black red green yellow blue black black black
```
![term](https://user-images.githubusercontent.com/30186515/87165254-91027700-c2d2-11ea-9257-b4e6a86a927b.png)

I personally think a good solution would be to take for example tomorrow light colors and tweak them a little if they don't look nice.

**Comment by cideM** [comment]
I have 2 days off so I'll tackle this tomorrow and/or friday

**Comment by cideM** [comment]
I think I can fix this tomorrow by simply using the colors already in the theme for git diffs and errors and adding whichever colors are missing

**Comment by cideM** [comment]
I pushed a commit which adds the 2 missing colors magenta and cyan and uses existing colors for the rest. Didn't test this extensively but it should hopefully be better than what's used for Term colors right now
