### ISSUE TITLE
Version 1 Rewrite

### ISSUE THREAD

**Issue by cideM** [cideM/yui#20]
I've created a branch on which I'm reimplementing large parts of this color scheme. It will keep its overall brownish vibe from the Rams notebook but it'll be a bit less brown. Here's what I have in mind:

- [ ] Pay more attention to impaired color vision
- [ ] Better constrast so working in flux/redshift is easier
- [ ] Remove all options... I think a color scheme should just have a good overall vision and concept and then come omakase. It's really hard to make sure that all options are compatible to each other
- [ ] Remove the `colortemplate` dependency. I read in an [issue](https://github.com/lifepillar/vim-colortemplate/issues/43) that there are ideas to "Rewrite Colortemplate in Vim9 script." and as a Neovim user I'd like to keep things compatible with both. Also I think I'm not getting enough value out of it. There are a lot of options for templating.
- [ ] More support for 3rd party plugins and highlight groups not covered by the current version

All of these are just ideas so far. I'll post updates and screenshots in this issue. Feel free to chime in! All feedback is appreciated.

One of the most important things I'm playing around with right now are comments. I really don't t like the orange I have on `master` and I'm considering giving them a certain background shade. Only italic is also an option but that's easy to miss maybe? Although it would have a certain minimalistic appeal if comments had only italic text and nothing else 🥥

**Comment by cideM** [comment]
<img width="834" alt="Screen Shot 2021-01-06 at 21 07 12" src="https://user-images.githubusercontent.com/4246921/103815124-2f457e80-5063-11eb-9d3a-0cc25d49f0fe.png">
<img width="982" alt="Screen Shot 2021-01-06 at 21 07 18" src="https://user-images.githubusercontent.com/4246921/103815132-3076ab80-5063-11eb-9808-295e1a7a8cac.png">

**Comment by eemed** [comment]
I tested the v2 branch here are my experiences:

* I really liked the blue color on `Search`. Infact I even linked `PMenuSel` and `Visual` to `Search`.
* I liked the old background color but after watching the new one for about 5 mins it seems good too.
* Comments are good I always wanted them to be significantly different than other text
* `Statusline` is better with dark background
* Would still like an option to change `LineNr` and `SignColumn` background to something different than `Normal`
* I dont like the bold on `WarningMsg` and `ErrorMsg`. Also I don't know if you changed the colors or not but they seem to really disappear to the background.
* Again don't know if this is about the background but diff colors were the best thing about this colorscheme when I started I would like them back if possible. Especially `diffAdded` blends into the background.
* `Todo` is great.

Some further ideas since we are rewriting:
* I would like to add bold or something to `Keyword`. But this is the same as `Constant` so we would need to manage that somehow
* `MatchParen` should be something more significant

**Comment by cideM** [comment]
Thanks for the feedback!

> Also the previous emphasized Comment orange was beautiful maybe you can reuse it.

This won't work because it really doesn't work when using redshift/flux/nightshift

> I dont like the bold on WarningMsg and ErrorMsg

Hm yeah it's a bit overkill I think I'll change that back to non bold

> MatchParen should be something more significant

Ideas? I personally like it subtle, maybe there's some nice middle ground here

> Especially diffAdded blends into the background.

I'll take a look at the contrast ratios for these

**Comment by eemed** [comment]
> You mean the purple from the last screenshots on `master`?

Yea it probably was purple in code, but looked blue to me.

> Ideas? I personally like it subtle, maybe there's some nice middle ground here

I linked `MatchParen`  to the `Search` purple, but thats probably too much if you want it subtle. Maybe just use a darker background with normal foreground color? I usually search pairs using this and usually miss them if only the foreground is changed.

> Maybe I can use a color for selections and search to unify all sorts of "select this thing and make it stand out"

This is exactly what I did in my configs with the previous `Search` purple and it looked great.

**Comment by cideM** [comment]
I brought back the purple, it's also much better for red shift as the orangy/salmony color I had before

Also made diffAdd a bit greener

**Comment by cideM** [comment]
<img width="735" alt="Screen Shot 2021-01-14 at 23 01 46" src="https://user-images.githubusercontent.com/4246921/104654506-80392080-56bc-11eb-9970-fee247c91491.png">

Here's blue comments and colored sidebar. The purple doesn't look nice for comments. Having comments and sidebar with a background can make for A LOT of backgrounds

**Comment by eemed** [comment]
Hmm... The comments were the best with different background. I would keep them for now. 

Maybe try to use the purple in selections as you suggested.

About the keyword highlighting:
Maybe like you said keywords bold and strings slightly different foreground color.
Maybe even just italic the keywords and keep strings bold?
I think the first would look better.

**Comment by cideM** [comment]
The problem about comments with background is that there's a lot of background when the sidebar (signcolumn linenr) also has a background

**Comment by eemed** [comment]
Yea im experimenting currently. The second problem is that the background disappears with cursorline.

**Comment by cideM** [comment]
Here's another issue with comments that have backgrounds
<img width="213" alt="Screen Shot 2021-01-15 at 12 45 37" src="https://user-images.githubusercontent.com/4246921/104723563-b6fc4e80-572f-11eb-9fa8-869af29f9cd2.png">


Tabs in comments

**Comment by eemed** [comment]
I also had alot of problems with `CursorLine` but it should resolve itself by not linking anything to `Normal`

**Comment by eemed** [comment]
What do you think about the blue/purple visual selection and psel?

**Comment by cideM** [comment]
I actually mentioned that a few comments ago it was just obscured by all the screenshots. I think I already pushed something that uses blue/purple (also called blurple) again. I just haven't added it for visual yet. I'll have to see if that makes `hlsearch` difficult. I'm part of a minority of users who doesn't auto deactivate `hlsearch` upon cursor movement and so for me it might be useful to differntiate visual select from hlsearch

**Comment by cideM** [comment]
<img width="664" alt="Screen Shot 2021-01-16 at 22 56 41" src="https://user-images.githubusercontent.com/4246921/104823932-223c4280-584e-11eb-86f8-4bc28c7677af.png">

Another comment idea. Has to be bold for it to at least be AA contrast

**Comment by eemed** [comment]
That looks good. But if we link Visual to blue also there will be so much of it

**Comment by cideM** [comment]
The all purple version
<img width="876" alt="Screen Shot 2021-01-18 at 18 19 27" src="https://user-images.githubusercontent.com/4246921/104945972-b8d94280-59b9-11eb-86b8-1967e512ce50.png">

**Comment by eemed** [comment]
Yeah the comments add too much purple

**Comment by cideM** [comment]
My current idea is to go back to not having the sidebar colored. This theme was inspired by a paper notebook which also doesn't have any special sidebar. And then instead of adding options I'll add a FAQ with snippets that show people how to get a colored sidebar by linking highlight groups. This empowers people to learn a bit about Vim colorschemes, is very flexible and doesn't put more burned on this colorscheme.

Then I can give comments a background again (with some other change the tab issue seems gone) and even make them non-italic. After all, they're already set apart by their bg color.

This would free up italics for e.g., identifiers.

<img width="789" alt="Screen Shot 2021-01-19 at 10 03 45" src="https://user-images.githubusercontent.com/4246921/105011779-a30d6100-5a3d-11eb-83ac-f74255871736.png">

**Comment by eemed** [comment]
Yeah that looks better. The only problem with background comments is that if you use cursorline the color doesnt immediately tell that you are in a comment. But thats just a small inconvenience

**Comment by eemed** [comment]
Now that comments are no longer italic. and strings have a different foreground instead of bold. What would you want to use bold and italic for?


I would like to all language constructs to be bold, but don't really know what italic is good for. Currently im pretty happy with the theme and my modifications have reduced to 
```vim
highlight! link SpecialComment Comment
highlight! Statement gui=bold
highlight! SignColumn guibg=#EBE2E0
```

Lsp settings are off however. Floating windows have error colored text and some signs have no color. Im still using these
```vim
highlight! link LspDiagnosticsSignError ErrorMsg
highlight! link LspDiagnosticsSignWarning WarningMsg
highlight! link LspDiagnosticsSignInformation Search
highlight! link LspDiagnosticsSignHint Search

highlight! link LspDiagnosticsDefaultError NormalFloat
highlight! link LspDiagnosticsDefaultWarning NormalFloat
highlight! link LspDiagnosticsDefaultInformation NormalFloat
highlight! link LspDiagnosticsDefaultHint NormalFloat

highlight! link LspDiagnosticsUnderlineError SpellBad
highlight! link LspDiagnosticsUnderlineWarning DiffChange
highlight! LspDiagnosticsUnderlineInformation cterm=NONE gui=NONE
highlight! LspDiagnosticsUnderlineHint cterm=NONE gui=NONE
```
I don't know if those highlight groups are the final ones in neovim 0.5 but they seem to work for me currently.

**Comment by cideM** [comment]
Better visibility for tab line
Differentiate hlsearch and visual by using a shade of purple

![2021-02-16T12:02:29,734646739+01:00](https://user-images.githubusercontent.com/4246921/108054453-f4b20700-704e-11eb-8fce-3eddca51170b.png)
![2021-02-16T12:02:41,205722956+01:00](https://user-images.githubusercontent.com/4246921/108054455-f54a9d80-704e-11eb-91ee-0602f0e68023.png)

**Comment by cideM** [comment]
:wave: I've done some reflecting and came to a few conclusions.

I will abandon the idea of a rewrite with breaking changes. I'm always annoyed by breaking changes without a really good reason. As it stands, the V1 version I'm proposing here isn't some scientific and artistic miracle that would warrant that. I'll therefore keep all options the way they are right now so one using this color scheme has to change anything.

I'll port the improvements made from the `v2` branch to `master`. This includes additional highlight groups for third party plugins and any obvious improvements to existing colors.

I might keep some tweaks to foreground and background, depending on the contrast of the current FG and BG colors. But nothing drastic.

Lastly, I'll replace the `colortemplate` dependency with a light-weight, custom solution. Probably a single Nix shebang file using Haskell. That way I can use http://hackage.haskell.org/package/colour-2.3.5 to mix, dark and blend colors, and so on. Manually doing this kind of shading is tedious.

**Comment by cideM** [comment]
It's a few hundred lines of easily manageable Vim script so I've even abandoned the idea of any custom light weight templating thing.
