### ISSUE TITLE
gui powershell pipe and forward slash look really similar

### ISSUE THREAD

**Issue by jmzagorski** [cideM/yui#21]
Thank you for such a simple light colorscheme. I just switched over and am pleasantly surprised by how much I enjoy it so far.

I have been doing some powershell development and noticed that the pipe character looks a little bit like a forward slash, though there is a difference when they are next to each other. When i run `hi clear Statement` it looks like a pipe again since the italic is removed. Do you notice this in .ps1 files, and if so do you think an exception should be added for this in the library or should this be set in our own `autocmd`? Thank you

The image below shows the pipe:

![yui-colorscheme-powershell-pipe](https://user-images.githubusercontent.com/8404957/126180940-0ba17e30-5e25-4f20-963f-372233e67b5f.PNG)

**Comment by cideM** [comment]
Thanks for the issue! This is definitely something that should be done differently. I'll add an exception in the color scheme itself later today

**Comment by cideM** [comment]
@jmzagorski I just pushed a change were keyword, label, repeat, operator and exception are no longer linked to statement (which is italic) but rather to normal. `Operator` is what caused the italic `|` in this case here

**Comment by jmzagorski** [comment]
Just pulled down the new code, looks good! Thank you.
