### ISSUE TITLE
Add ability to use colorscheme in lightline

### ISSUE THREAD

**Issue by mambusskruj** [cideM/yui#22]
Hi! 

Lightline is a popular light and configurable statusline/tabline plugin for Vim. – https://github.com/itchyny/lightline.vim

Lightline provides ability to configure colors for theme developers. Here's example for popular vim theme called **gruvbox**: https://github.com/morhetz/gruvbox/blob/master/autoload/lightline/colorscheme/gruvbox.vim

Would you mind to add colors for lightline in yui?

**Comment by cideM** [comment]
Glad you like it 👍🏻 thank you. Sounds like a reasonable request I'll try to take care of it ASAP

**Comment by cideM** [comment]
I started working on this and I'll have a branch ready for you to try tomorrow, sorry for the delay

**Comment by mambusskruj** [comment]
Hey! Hmm, I get error:
```
lightline.vim: Could not load colorscheme yui.
```

I see lightline block in `colors/yui.vim`

**Comment by mambusskruj** [comment]
Look good!

Personally I'm not sure about bold text. For reference, lightline's solarized theme doesn't get any bold text, and it looks sharper to me. https://github.com/itchyny/lightline.vim#solarized-backgroundlight
![image](https://user-images.githubusercontent.com/15351892/163693281-4b1393e6-5d52-4571-ae7a-b57cec1cea94.png)


But it's all of your taste ofc. :) So for me it already looks very nice!

**Comment by cideM** [comment]
I agree that the solarized theme without bold text looks better. I'll take another look and tweak some colors and remove the bold, just need to make sure that contrast is good enough

**Comment by cideM** [comment]
@mambusskruj I pushed another commit to the branch which removes the bold

**Comment by mambusskruj** [comment]
Love it! Thank you, it looks very clear and pretty.

**Comment by cideM** [comment]
@mambusskruj I updated the documentation and made sure that the colorscheme uses the documented option. Would it be possible for you to check this again? I verified that the colorscheme works with and without lightline and that people can still use other lightline color schemes even when `yui_lightline = v:true`

### `g:yui_lightline`

- `v:false` (**default**): do not register the `yui` palette with `lightline`
- `v:true`: do not register the `yui` palette with `lightline`. You still need
  to set the lightline color scheme to `yui`.

```vimscript
let g:yui_lightline = v:true
colorscheme yui
let g:lightline = {
  \ 'colorscheme': 'yui'
  \ }
```

**Comment by mambusskruj** [comment]
> Would it be possible for you to check this again?

Checked it. Yes, it works as you described it!
