### ISSUE TITLE
telescope: make found query visibly selected

### ISSUE THREAD

**Issue by mambusskruj** [cideM/yui#28]
I think it will be an UX improvement, to see what part was found exactly.

Here's how it looks with yui:
<img width="1486" alt="Screenshot 2023-04-05 at 11 36 08" src="https://user-images.githubusercontent.com/15351892/230028838-5338c674-1253-4c11-b11e-3fcd5cbe91fc.png">

And here's how it looks with other theme:
<img width="1486" alt="Screenshot 2023-04-05 at 11 37 31" src="https://user-images.githubusercontent.com/15351892/230028957-9f01add6-cfbd-4125-8195-190bfee6d3a9.png">

**Comment by cideM** [comment]
Seems very reasonable. I don't personally use Telescope but I can install it and see. You could try to make this change yourself in the meantime. Let me know if you need any information. I think I'll have capacity for this on Sunday.

**Comment by mambusskruj** [comment]
@cideM I'll try to implement it before Sunday, 'll see how it goes.
