### ISSUE TITLE
Invalid character in group name in colors/yui.vim

### ISSUE THREAD

**Issue by jmzagorski** [cideM/yui#35]
Hello @cideM - Thanks for a great plugin! This is the longest I've stayed on a colorscheme since I started with vim and don't have any plans to change

I updated my plugins today and ran across this error:

> Error detected while processing yui/colors/yui.vim:
> line 229: Invalid Character in group name
> line 230:: Invalid Character in group name

Which are these two line:
```vimscript
" Help Text TS
hi! link @text.literal helpExample
hi! link @text.reference helpOption
```

**Version**: VIM 9.0.1462 (compiled 4/17 2023, so pretty new patch)

**Comment by cideM** [comment]
Ah my bad those are probably not defined for Vim! I fixed this now with the most recent commits, can you check? Sorry about the inconvenience 🙏🏻

**Comment by jmzagorski** [comment]
Those errors are gone. Thank you for great support!
