### ISSUE TITLE
vim :colorscheme reports default

### ISSUE THREAD

**Issue by jmzagorski** [cideM/yui#59]
In https://github.com/cideM/yui/commit/897bb19c331347ec58d89fedacbc4afe98ccc8c5 `let g:colors_name = 'yui'` was removed, which is used by vim to report the colorscheme with `:colorscheme`. I wasn't sure if this was breaking something else because I do not use neovim, and I did not see anything in the commit message about it. Can this be brought back? I am using **Vi IMproved 9.1 (2024 Jan 02, compiled Jan 03 2024 01:25:17)**

Thanks again, been using this plugin for years. You removed my paradox of choice when it comes to vim colorschemes!

**Comment by cideM** [comment]
Thank you so much for the report! This was indeed an admittedly embarassing oversight on my part. Fixed in #60
