### ISSUE TITLE
How to change color of cursor? 

### ISSUE THREAD

**Issue by zavvdev** [cideM/yui#71]
Is there any way to change cursor color for insert and normal mode? In my case it's always white 
<img width="205" alt="Screenshot 2024-11-12 at 9 38 10 PM" src="https://github.com/user-attachments/assets/21904b8a-de68-4ff7-b808-e0da8a6275ed">

**Comment by cideM** [comment]
This should be done in your terminal. Normally Neovim doesn't control your cursor color. See https://github.com/cideM/yui/issues/70

**Comment by zavvdev** [comment]
> This should be done in your terminal. Normally Neovim doesn't control your cursor color. See #70

thank you!
